/** Application-wide constants */

const ROLES = {
  DLAO: 'DLAO',     // District Land Acquisition Officer
  PIA: 'PIA',       // Project Implementing Agency
  SGA: 'SGA',       // Senior Government Authority
  FRO: 'FRO',       // Field / Revenue Officer
  ADMIN: 'ADMIN',   // System Admin
};

const ROLE_LABELS = {
  DLAO: 'District Land Acquisition Officer',
  PIA: 'Project Implementing Agency',
  SGA: 'Senior Government Authority',
  FRO: 'Field / Revenue Officer',
  ADMIN: 'System Administrator',
};

const PROJECT_STATUS = {
  PROPOSED: 'PROPOSED',
  APPROVED: 'APPROVED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CLOSED: 'CLOSED',
};

const ACQUISITION_STATUS = {
  PROPOSED: 'PROPOSED',
  NOTIFIED: 'NOTIFIED',
  UNDER_ACQUISITION: 'UNDER_ACQUISITION',
  ACQUIRED: 'ACQUIRED',
  POSSESSION_TAKEN: 'POSSESSION_TAKEN',
  RR_ISSUE: 'RR_ISSUE',
};

const WORKFLOW_STAGES = {
  PROJECT_PROPOSAL: 'PROJECT_PROPOSAL',
  LAND_IDENTIFICATION: 'LAND_IDENTIFICATION',
  VERIFICATION: 'VERIFICATION',
  APPROVAL: 'APPROVAL',
  NOTIFICATION: 'NOTIFICATION',
  COMPENSATION: 'COMPENSATION',
  AWARD: 'AWARD',
  PAYMENT: 'PAYMENT',
  POSSESSION: 'POSSESSION',
  RR: 'RR',
  CLOSURE: 'CLOSURE',
};

const WORKFLOW_STAGES_ORDER = [
  'PROJECT_PROPOSAL',
  'LAND_IDENTIFICATION',
  'VERIFICATION',
  'APPROVAL',
  'NOTIFICATION',
  'COMPENSATION',
  'AWARD',
  'PAYMENT',
  'POSSESSION',
  'RR',
  'CLOSURE',
];

const WORKFLOW_ACTIONS = {
  APPROVE: 'APPROVE',
  FORWARD: 'FORWARD',
  SEND_BACK: 'SEND_BACK',
  REJECT: 'REJECT',
  COMPLETE: 'COMPLETE',
};

const CASE_STATUS = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  SENT_BACK: 'SENT_BACK',
  REJECTED: 'REJECTED',
};

const COMPENSATION_STATUS = {
  NOT_ASSESSED: 'NOT_ASSESSED',
  ASSESSED: 'ASSESSED',
  APPROVED: 'APPROVED',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  FULLY_PAID: 'FULLY_PAID',
};

const POSSESSION_STATUS = {
  NOT_TAKEN: 'NOT_TAKEN',
  PARTIAL: 'PARTIAL',
  TAKEN: 'TAKEN',
};

const DOCUMENT_TYPES = {
  LAND_RECORD: 'LAND_RECORD',
  SURVEY_REPORT: 'SURVEY_REPORT',
  NOTIFICATION: 'NOTIFICATION',
  AWARD_ORDER: 'AWARD_ORDER',
  COMPENSATION_DOC: 'COMPENSATION_DOC',
  POSSESSION_DOC: 'POSSESSION_DOC',
  RR_EVIDENCE: 'RR_EVIDENCE',
  OTHER: 'OTHER',
};

const ALERT_TYPES = {
  DEADLINE_APPROACHING: 'DEADLINE_APPROACHING',
  DEADLINE_MISSED: 'DEADLINE_MISSED',
  OVERDUE: 'OVERDUE',
  MISSING_DOC: 'MISSING_DOC',
  DATA_MISMATCH: 'DATA_MISMATCH',
  ESCALATION: 'ESCALATION',
  HIGH_RISK: 'HIGH_RISK',
};

const PRIORITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
};

const FAMILY_CATEGORY = {
  AFFECTED: 'AFFECTED',
  DISPLACED: 'DISPLACED',
};

const RR_STATUS = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  DELAYED: 'DELAYED',
};

const MISMATCH_SEVERITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
};

const MISMATCH_STATUS = {
  DETECTED: 'DETECTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  RESOLVED: 'RESOLVED',
  FALSE_POSITIVE: 'FALSE_POSITIVE',
};

module.exports = {
  ROLES,
  ROLE_LABELS,
  PROJECT_STATUS,
  ACQUISITION_STATUS,
  WORKFLOW_STAGES,
  WORKFLOW_STAGES_ORDER,
  WORKFLOW_ACTIONS,
  CASE_STATUS,
  COMPENSATION_STATUS,
  POSSESSION_STATUS,
  DOCUMENT_TYPES,
  ALERT_TYPES,
  PRIORITY,
  FAMILY_CATEGORY,
  RR_STATUS,
  MISMATCH_SEVERITY,
  MISMATCH_STATUS,
};
